// Generated from packages/provider/promotions.json by
// scripts/generate-promotions.mjs. Edit the JSON and run
// `npm run promotions:generate`; do not edit this file.
//
// The document stays `unknown` on purpose: it is data from a file people edit
// by hand, so the runtime normalizer in promotions.ts is its only gate.
export const BUNDLED_PROMOTIONS: unknown = {
  "version": 1,
  "updated": "2026-09-04",
  "notes": "Shared promotional windows. Vendor campaigns appear in no host's status payload and change without notice, so they are maintained here by pull request instead of being hardcoded in the runtime. Clock times are UTC unless a window sets \"timezone\". This list ships empty on purpose: an unverified window is worse than no badge. See the README for the field reference.",
  "promotions": []
};
